{{- if .Values.gatewayApi.enabled -}}
{{- $fullName := include "channel-proxy.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "channel-proxy.labels" . | nindent 4 }}
  {{- with .Values.gatewayApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- with .Values.gatewayApi.hostnames }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gatewayApi.gatewayName }}
      namespace: gateways
      sectionName: https-default
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}
          port: {{ $svcPort }}
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
