{{- if .Values.secrets }}
{{- range $name, $data := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "channel-proxy.fullname" $ }}-{{ $name }}
  labels:
    {{- include "channel-proxy.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
