{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "channel-proxy.fullname" . }}
  labels:
    {{- include "channel-proxy.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "channel-proxy.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    {{- with .Values.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.path }}
    path: {{ . }}
    {{- end }}
{{- end }}
